### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by GWillmann** [macminiosx/wordpress-ja-pg4wp2-heroku#2]
Hi there,

thank you for your work!

Can we safely update to wordpress 4.7 ? 
When I try to update, I always get the error message "Another update is currently in progress."

Even when I delete the record in _core_updater.lock_ in my database :/

Best,

**Comment by macminiosx** [comment]
Hi GWillmann

I updated wordpress 4.7-ja now.
plz try it.

**Comment by GWillmann** [comment]
Perfect thank you ! It works like a charm !
My best wishes for this new year.
