### ISSUE TITLE
Wordpress doesn't show option to add Plugins

### ISSUE THREAD

**Issue by roundrobin** [macminiosx/wordpress-ja-pg4wp2-heroku#3]
Any clues why this is the case in the default setup I followed?

**Comment by macminiosx** [comment]
Hi roundrobin.

You need push to heroku.

heroku git:clone -a <YOUR-APP-NAME>

git remote add origin https://github.com/macminiosx/wordpress-ja-pg4wp2-heroku/

and add Plugins into wp-content/plugins/

git add .

git commit -m 'add plugins'

git push heroku master

**Comment by roundrobin** [comment]
I just saw the little comment in the README about it. Not being able to write to disk also means that updates of Wordpress need to be done manually right?

**Comment by GWillmann** [comment]
Yes exactly. 
Each time you want to apply an update, you have to pull it, update it locally and then push it on Heroku.
