### ISSUE TITLE
What is ADMINAUTH Login Basic authentication

### ISSUE THREAD

**Issue by adilmalik393** [macminiosx/wordpress-ja-pg4wp2-heroku#4]
What is this field. When I am done deploying and installing wordpress. An authentication dialog comes and ask for username and password. And i have put the wordpress credentials as well as other credentials that were asked when i was about to deploy the app. Not sure what to do .

**Comment by macminiosx** [comment]
wordpressのログインをよりsecureにするためにbasic認証を入れてます。
日本では当たり前のことです。
htpasswd のGeneratorはこちらです。
http://www.macminiosx.com/generator/htpasswd_generator.html

もし basic認証が必要でないならば、.htaccessの
<Files wp-login.php>
AuthName "Login Password Required"
AuthType Basic
AuthUserFile /app/.htpasswd
require valid-user
</Files>
を削除してください。

**Comment by GWillmann** [comment]
@adilmalik393 as @macminiosx said, it is an additional mean of authentification in order to protect the private pages of wordpress. You may remove it should you think it is not necessary...

**Comment by adilmalik393** [comment]
@macminiosx your link for htpasswd_generator is not working. 
@GWillmann How can i remove this, Please explain

**Comment by macminiosx** [comment]
sorry,
htpasswd Generator new link is:
https://macminiosx.github.io/passwd-generator/

$ heroku config:set ADMINAUTH=encrypt pssword

You can also edit config vars on your app's settings tab on Heroku Dashboard.

**Comment by GWillmann** [comment]
@adilmalik393 to remove the authentication juste delete those lines in the _.htaccess_ file :   
    
```
AuthName "Login Password Required"
AuthType Basic
AuthUserFile /app/.htpasswd
require valid-user```
